### ISSUE TITLE
Create symlinker script for quicklisp systems

### ISSUE THREAD

**Issue by alex-eg** [koto-bank/lbge#1]
Create a bash script, something like `quicklisp-symlink` to automatically create symlinks in `~/quicklisp/local-systems` for the engine system and all systems from `a` directory.

**Comment by vaartis** [comment]
One doesn't actually need to do anything complicated, since quicklisp checks all directories recursively and will see all systems in all directories, if the root repository directory is symlinked to `local-projects`.
