### ISSUE TITLE
Add ability to disable tests somehow to unittest app

### ISSUE THREAD

**Issue by alex-eg** [koto-bank/lbge#28]
I think the most cool way is to enable test authors to mark their tests as disabled, so we won't run rove for them.
It can be done by exporting some symbol from package, e.g. `*disabled*`, which should govern if test is disabled or not.

So, if there's no symbol `*disabled*` in test package, we consider the test enabled.
If the symbol is present, we check its value, and don't run if it is t.
Rationale: during debug it might come in handy to be able to toggle tests, and uninterning a symbol is certrainly a more complex operation than setting a value.

**Comment by pkulev** [comment]
https://github.com/fukamachi/rove#skip-description

**Comment by alex-eg** [comment]
I meant whole test suites, which are designated as packages in the current architecture.
So if several `deftests` are defined in some package, and none of them work, it seems useful to have an ability to skip the whole package.

**Comment by alex-eg** [comment]
Closed in #36
